---------------------------------------------------------------------
-- Licensed Materials - Property of IBM
--
-- Governed under the terms of the International
-- License Agreement for Non-Warranted Sample Code.
--
-- (C) COPYRIGHT International Business Machines Corporation 2009
-- All Rights Reserved.
--
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
---------------------------------------------------------------------

SET CURRENT SCHEMA = 'DB2XML';

DROP FUNCTION httpGetBlob;
DROP FUNCTION httpGetClob;
DROP FUNCTION httpPutBlob;
DROP FUNCTION httpPutClob;
DROP FUNCTION httpPostBlob;
DROP FUNCTION httpPostClob;
DROP FUNCTION httpDeleteClob;
DROP FUNCTION httpDeleteBlob;
DROP FUNCTION httpHead;
DROP FUNCTION httpBlob;
DROP FUNCTION httpClob;
DROP FUNCTION urlEncode;
DROP FUNCTION urlDecode;
DROP FUNCTION base64Encode;
DROP FUNCTION base64Decode;

CREATE FUNCTION urlEncode(value VARCHAR(2048), encoding VARCHAR(20))
RETURNS VARCHAR(4096)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.urlEncode'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
NOT VARIANT
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION urlDecode(value VARCHAR(2048), encoding VARCHAR(20))
RETURNS VARCHAR(4096)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.urlDecode'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
NOT VARIANT
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION base64Encode(in VARCHAR(2732) FOR BIT DATA)
RETURNS VARCHAR(4096)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.base64Encode'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
NOT VARIANT
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION base64Decode(in VARCHAR(4096))
RETURNS VARCHAR(2732) FOR BIT DATA
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.base64Decode'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
NOT VARIANT
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpHead(url VARCHAR(2048), httpHeader CLOB (10K))
RETURNS CLOB(10K)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpHead'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;


CREATE FUNCTION httpGetBlob(url VARCHAR(2048), httpHeader CLOB (10K))
RETURNS BLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpGetBlob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpGetClob(url VARCHAR(2048), httpHeader CLOB (10K))
RETURNS CLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpGetClob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpPutBlob(url VARCHAR(2048), httpHeader CLOB (10K), 
                            requestMsg BLOB(5M))
RETURNS BLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpPutBlob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpPutClob(url VARCHAR(2048), httpHeader CLOB (10K), 
                            requestMsg CLOB(5M))
RETURNS CLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpPutClob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpPostBlob(url VARCHAR(2048), httpHeader CLOB (10K), 
                             requestMsg BLOB(5M))
RETURNS BLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpPostBlob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpPostClob(url VARCHAR(2048), httpHeader CLOB (10K), 
                             requestMsg CLOB(5M))
RETURNS CLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpPostClob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpDeleteBlob(url VARCHAR(2048), httpHeader CLOB (10K))
RETURNS BLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpDeleteBlob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpDeleteClob(url VARCHAR(2048), httpHeader CLOB (10K))
RETURNS CLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpDeleteClob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpBlob(url VARCHAR(2048), httpMethod VARCHAR(128), 
                         httpHeader CLOB (10K), requestMsg BLOB(5M))
RETURNS BLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpBlob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;

CREATE FUNCTION httpClob(url VARCHAR(2048), httpMethod VARCHAR(128), 
                         httpHeader CLOB (10K), requestMsg CLOB(5M))
RETURNS CLOB(5M)
EXTERNAL NAME 'com.ibm.db2.rest.DB2UDFWrapper.httpClob'
LANGUAGE JAVA
PARAMETER STYLE JAVA
PARAMETER CCSID UNICODE
CALLED ON NULL INPUT
NO SQL
WLM ENVIRONMENT WLMENVJ
PROGRAM TYPE SUB;
